name: Test and Tag

on:
  push:
    branches:
      # explicit deny all here to make sure there isnt a commit loop
      - '!*'
      - main

jobs:
  test_and_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: check if tag already exists
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/* && git rev-parse "$(cat VERSION)" >/dev/null 2>&1 && exit 1 || exit 0

      - name: create test file
        run: echo $(date) > tmp.txt

      - name: create test directory
        run: mkdir -p tmp && cp tmp.txt tmp && echo "second cool file" > tmp/tmp2.txt

      - name: test with file
        uses: ./
        id: filetest
        with:
          source: tmp.txt
          destination_repo: leigholiver/commit-with-deploy-key
          destination_branch: file_test
          deploy_key: ${{ secrets.DEPLOY_KEY }}

      - name: test commit hash output
        run: echo "the commit hash for the file test is ${{ steps.filetest.outputs.commit_hash }}"

      - name: test with directory
        uses: ./
        with:
          source: tmp
          destination_repo: leigholiver/commit-with-deploy-key
          destination_branch: directory_test
          deploy_key: ${{ secrets.DEPLOY_KEY }}

      - name: test destination directory
        uses: ./
        with:
          source: tmp
          destination_repo: leigholiver/commit-with-deploy-key
          destination_branch: destination_directory_test
          destination_folder: destination
          deploy_key: ${{ secrets.DEPLOY_KEY }}

      - name: test destination directory with removal
        uses: ./
        with:
          source: tmp
          destination_repo: leigholiver/commit-with-deploy-key
          destination_branch: destination_directory_test_with_delete
          delete_destination: true
          deploy_key: ${{ secrets.DEPLOY_KEY }}

      - name: test with different username
        uses: ./
        with:
          source: tmp.txt
          destination_repo: leigholiver/commit-with-deploy-key
          destination_branch: username_test
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          git_username: some different user

      - name: test with different commit message
        uses: ./
        with:
          source: tmp.txt
          destination_repo: leigholiver/commit-with-deploy-key
          destination_branch: commit_message_test
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          commit_message: testing a custom commit message (${{ github.sha }})

      - name: create tag
        run: git config --global user.email "${{ github.actor }}" && git config --global user.name "${{ github.actor }}" && git tag -a -m "$(cat VERSION)" $(cat VERSION) && git push --follow-tags
